/*

 HUD_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\kempc\Documents\gb\gbc\botw2d\hud.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hud_mapWidth 20
#define hud_mapHeight 18
#define hud_mapBank 0

extern unsigned char hud_map[];

/* End of HUD_MAP.H */
